# Add your GitHub Sponsors username or other platforms here if needed.
# For now, this is intentionally left blank.

# github: [npazzaglia]
# patreon: your-patreon
# ko_fi: your-kofi
# open_collective: your-opencollective
# custom: ['https://buymeacoffee.com/yourname']