name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true  # Safe default

      - name: Lint
        run: |
          pip install flake8 || true
          flake8 . || echo "Linting failed but not blocking in template"

      - name: Run tests
        run: |
          pip install pytest || true
          pytest tests || echo "Tests not present (yet)"