name: Post-Fork Self Check

on:
  push:
    branches: [main]

jobs:
  validate:
    name: Validate Post-Fork Bootstrap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check post-fork.sh exists
        run: |
          test -f bin/post-fork.sh && echo "✅ Found post-fork.sh"
      - name: Check config
        run: |
          grep DEFAULT_VERSION bin/post-fork.conf
